# ArgoCD/Helm merge theo key transfer-service
transfer-service:
  fullnameOverride: transfer-service
  enabled: true
  image:
    repository: registry.gitlab.com/ninhductoan52/banking-demo-payment/transfer-service
    tag: 6194f85
    pullPolicy: Always
  imagePullSecrets: []
  replicas: 2
  service:
    port: 8003
    portName: http
  secretRef:
    name: banking-db-secret
    keys:
      databaseUrl: DATABASE_URL
      redisUrl: REDIS_URL
  # # Phase 8: RABBITMQ_URL từ Secret (consumer v3)
  # rabbitmqSecretRef:
  #   name: rabbitmq-connection-secret
  #   key: RABBITMQ_URL
  corsOrigins: "http://localhost:3000"
  # OpenTelemetry tracing → gửi traces về otel-collector → Tempo
  extraEnv:
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
  readinessProbe:
    enabled: true
    path: /health
    port: 8003
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "600m"
  securityContext:
    pod:
      seccompProfile:
        type: RuntimeDefault
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
