apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-phase4
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-demo
    app.kubernetes.io/part-of: banking-demo-phase4
spec:
  project: banking-demo-phase4
  source:
    repoURL: https://github.com/ntoa25001/banking-demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo
    helm:
      releaseName: banking-demo
      valueFiles:
        - charts/common/values.yaml
        - charts/postgres/values.yaml
        - charts/redis/values.yaml
        - charts/kong/values.yaml
        - charts/auth-service/values.yaml
        - charts/account-service/values.yaml
        - charts/transfer-service/values.yaml
        - charts/notification-service/values.yaml
        - charts/frontend/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m